- name: install memcached
  become: True
  apt:
    name: memcached
    cache_valid_time: "{{ cache_update_valid_secs }}"

- name: enable memcached
  become: True
  service:
   name: memcached
   enabled: yes
   state: started

- name: install Python memcached library
  become: True
  pip:
    name: pymemcache


